# Generated by Django 4.1.7 on 2023-04-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('WhitePlayerID', models.IntegerField()),
                ('BlackPlayerID', models.IntegerField()),
                ('Status', models.CharField(max_length=4, null=True)),
                ('Result', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameID', models.IntegerField()),
                ('PlayerID', models.IntegerField()),
                ('Cur_pos', models.CharField(max_length=4, null=True)),
                ('FigureKEY', models.CharField(max_length=8, null=True)),
                ('Status', models.CharField(max_length=8, null=True)),
            ],
            options={
                'db_table': 'moves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
    ]
