# Generated by Django 4.2 on 2023-04-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
