# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import move_pb2 as move__pb2


class send_moveStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getMoves = channel.unary_unary(
                '/send_move/getMoves',
                request_serializer=move__pb2.move.SerializeToString,
                response_deserializer=move__pb2.response.FromString,
                )


class send_moveServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getMoves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_send_moveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getMoves': grpc.unary_unary_rpc_method_handler(
                    servicer.getMoves,
                    request_deserializer=move__pb2.move.FromString,
                    response_serializer=move__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'send_move', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class send_move(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getMoves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/send_move/getMoves',
            move__pb2.move.SerializeToString,
            move__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
